spring.application.name=bus-api

## Tener en cuenta que se debe crear la base de datos CREATE DATABASE bus_db;

spring.datasource.url=jdbc:postgresql://localhost:5432/bus_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect